import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
  { path: 'about-us', loadComponent: () => import('./pages/about/about.component').then(m => m.AboutComponent) },
  { path: 'contact-us', loadComponent: () => import('./pages/contact-us/contact-us.component').then(m => m.ContactUsComponent) },
  { path: 'products', loadComponent: () => import('./pages/products/products.component').then(m => m.ProductsComponent) },
  { path: 'products/:productName', loadComponent: () => import('./pages/products/products.component').then(m => m.ProductsComponent) },
  { path: 'catalogue', loadComponent: () => import('./pages/catalogue/catalogue.component').then(m => m.CatalogueComponent) },
  { path: 'research', loadComponent: () => import('./pages/research/research.component').then(m => m.ResearchComponent) },
  { path: 'quality-assurance', loadComponent: () => import('./pages/quality-assurance/quality-assurance.component').then(m => m.QualityAssuranceComponent) },
  { path: 'product/emamectin-benzoate-5-sg', loadComponent: () => import('./pages/all-products/emamectin-benzoate-5-sg/emamectin-benzoate-5-sg.component').then(m => m.EmamectinBenzoate5SgComponent) },
  { path: 'product/proceed', redirectTo: 'product/emamectin-benzoate-5-sg', pathMatch: 'full' },
  { path: 'product/thiamethoxam-75-sg', loadComponent: () => import('./pages/all-products/thiamethoxam-75-sg/thiamethoxam-75-sg.component').then(m => m.Thiamethoxam75SgComponent) },
  { path: 'product/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc', loadComponent: () => import('./pages/all-products/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc.component').then(m => m.Thiamethoxam12_6LambdaCyhalothrin9_5ZcComponent) },
  { path: 'product/thio-h', redirectTo: 'product/thiamethoxam-75-sg', pathMatch: 'full' },
  { path: 'product/thiamethoxam-30-fs', loadComponent: () => import('./pages/all-products/thiamethoxam-30-fs/thiamethoxam-30-fs.component').then(m => m.Thiamethoxam30FsComponent) },
  { path: 'product/super-fs', redirectTo: 'all-products/thiamethoxam-30-fs', pathMatch: 'full' },
  { path: 'product/mpire-404', loadComponent: () => import('./pages/all-products/mpire-404/mpire-404.component').then(m => m.Mpire404Component) },
  { path: 'product/tolfenpyrad-15-ec', loadComponent: () => import('./pages/all-products/tolfenpyrad-15-ec/tolfenpyrad-15-ec.component').then(m => m.Tolfenpyrad15EcComponent) },
  { path: 'product/h-fun', redirectTo: 'product/tolfenpyrad-15-ec', pathMatch: 'full' },
  { path: 'product/glyphosate-41-sl', loadComponent: () => import('./pages/all-products/glyphosate-41-sl/glyphosate-41-sl.component').then(m => m.Glyphosate41SlComponent) },
  { path: 'product/glufosinate-ammonium-13-5-sl', loadComponent: () => import('./pages/all-products/glufosinate-ammonium-13-5-sl/glufosinate-ammonium-13-5-sl.component').then(m => m.GlufosinateAmmonium135SlComponent) },
  { path: 'product/quizalofop-ethyl-10-ec', loadComponent: () => import('./pages/all-products/quizalofop-ethyl-10-ec/quizalofop-ethyl-10-ec.component').then(m => m.QuizalofopEthyl10EcComponent) },
  { path: 'product/tembotrione-34-4-w-w-sc', loadComponent: () => import('./pages/all-products/tembotrione-34-4-w-w-sc/tembotrione-34-4-w-w-sc.component').then(m => m.Tembotrione344WwScComponent) },
  { path: 'product/paraquat-dichloride-24-sl', loadComponent: () => import('./pages/all-products/paraquat-dichloride-24-sl/paraquat-dichloride-24-sl.component').then(m => m.ParaquatDichloride24SlComponent) },
  { path: 'product/pendimethalin-30-ec', loadComponent: () => import('./pages/all-products/pendimethalin-30-ec/pendimethalin-30-ec.component').then(m => m.Pendimethalin30EcComponent) },
  { path: 'product/emamectin-benzoate-1-9-ec', loadComponent: () => import('./pages/all-products/emamectin-benzoate-1-9-ec/emamectin-benzoate-1-9-ec.component').then(m => m.EmamectinBenzoate19EcComponent) },
  { path: 'product/abamectin-1-9-ec', loadComponent: () => import('./pages/all-products/abamectin-1-9-ec/abamectin-1-9-ec.component').then(m => m.Abamectin19EcComponent) },
  { path: 'product/chlorpyriphos-20-ec', loadComponent: () => import('./pages/all-products/chlorpyriphos-20-ec/chlorpyriphos-20-ec.component').then(m => m.Chlorpyriphos20EcComponent) },
  { path: 'product/dr-supreme', redirectTo: 'product/abamectin-1-9-ec', pathMatch: 'full' },
  { path: 'product/round', redirectTo: 'product/glyphosate-41-sl', pathMatch: 'full' },
];
